// class solution {
// public:

// }
// {
// void maxarray(<int>& arr){
//     int arr = { };
//     int sum = 0; 

// class solution{
//     public:

//     void movesZeroes( <int>& arr){

//         int j = 0; 

//         for( int i = 0; i < arr.size(); i++){
//             if( arr[i] != 0)(
//          swap(arr[i],arr[j]);
            
//          j++;
//             }
//         }
     
//     }
// };

// class Solution{
//     public:

//     void max(vector<int>& nums , int k ){

//         int sum = 0;
//       
//         for( int i = 0; i < k; i++){
//       sum += nums[i];

//      maxi = sum;
// for( int k =0; k < arr.size(); k++);
//           sum = sum + arr[i] -num[i-k];
// maxi = max(maxi, sum);
//         }
//     }
// }

